### ISSUE TITLE
How to specify cfgFile when submitting?

### ISSUE THREAD

**Issue by whooooaami** [diambra/arena#102]
Hi!

I am trying to submit an agent with the following submission-manifest file:

```
mode: AIvsCOM
image: diambra/arena-stable-baselines3-on3.10-bullseye:main
command:
  - python
  - "/sources/agent.py"
  - "/sources/models/model.zip"
sources:
  .: git+https://username:{{.Secrets.token}}@github.com/username/repository_name.git#ref=branch_name
```

(where I have ommitted my username and repository_name for the sake of privacy here)

but diambra complains that no config file is being passed to agent.py. Which config file should we specify? The same that I used for training the agent? If yes, how do we specify it in this submission file?

Thank you!

**Comment by alexpalms** [comment]
Hi @whooooaami and thank you for reaching out!

Sorry for the late answer. Did you figure out how to correctly submit? If you are still encountering issues, I suggest you to reach out via our Discord server, there is a dedicated support channel there and the community can help too, together with us.

This is technically not an issue for the arena repo, so I would like to close it and address the topic on the server, ok? Looking forward for news from your side!

**Comment by alexpalms** [comment]
Solved, more info on the discord server ;)
