### ISSUE TITLE
Game Request: GGAC

### ISSUE THREAD

**Issue by Skenkel** [diambra/arena#16]
I used to play a number of these games, and I'm wondering what the process is for adding a game to this?
I'd really like to try this with guilty gear accent core, because it has a number of unique mechanics (one character controls two things on screen, one with button presses, one with button releases, there are animations for install kill attacks), and I'd like to explore RL within a space that I have some domain knowledge. 

Are there any docs or guides for adding a game?

**Comment by diambra** [comment]
Thank you @Skenkel for this request. Unfortunately at the moment we can only support games that are available through the MAME emulator. We are already planning super cool expansions, but dreamcast emulated games are not among them for now. To increase priority for features please comment them.
