### ISSUE TITLE
rom file

### ISSUE THREAD

**Issue by haisheng666** [diambra/arena#52]
I want to ask, what are the formats of the roms of those games? Where can I download it? Otherwise, the program will not run

**Comment by alexpalms** [comment]
Hi @haisheng666, 

the installation instructions for the ROMs are described here: https://docs.diambra.ai/#download-game-roms-and-check-validity

As you can see there, with the command `diambra arena list-roms` you obtain the list of available games, for each of them you have a list of keywords that you can use to search for the rom online, for example, for Dead Or Alive the list is:

`'DEAD OR ALIVE ++ [JAPAN]', 'dead-or-alive-japan', '80781', 'wowroms'`

using those ones you should be able to obtain the correct roms, that can be validated as described in the same section of the documentation at the previous link.

Let us know if you encounter any specific problem, or reach us on our discord server for specific help: https://discord.gg/tFDS2UN5sv
