### ISSUE TITLE
Unable to enter password

### ISSUE THREAD

**Issue by huyantao264** [diambra/arena#93]
*********************************

**Comment by discordianfish** [comment]
Can you login to diambra.ai with your email and password?

**Comment by huyantao264** [comment]
> 您可以使用您的电子邮件和密码登录 diambra.ai 吗？

Yes, I can log in to the website, but when I enter the password in the command line, the text is not displayed. I swear I have entered it more than ten times, but it keeps saying the password is incorrect. I can log in normally on the website.

**Comment by discordianfish** [comment]
@huyantao264 Does it work now?
